server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tiancheng?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true&&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin


#日志路径
logging:
  file:
    path: target/logging

process:
  startId: 5
  startName: 开始
  endId: 3
  endName: 结束
  userName: admin
  realName: 管理员

role:
  superAdmin: SUPER_ADMIN
  superAdminName: 超级管理员
  admin: ADMIN
  adminName: 系统管理员
  commonUser: COMMON_USER
  commonUserName: 普通用户

file:
  path: D://tiancheng/image/
  downLoadPath: http://192.168.101.12:8080/file/image/download?imageName={imageName}

